-- You can use this file to load seed data into the database using SQL statements
insert into Shopping (id, cidade, estado, logradouro, nome) values (1, 'Sao Paulo', 'SP', 'Av Raimundo Pereira de Magalhães', 'Shopping Grande Pirituba');
insert into loja (id, descricao, localizacao, nome, shopping_id, logo) values (10,'A Fast Shop é uma rede de lojas brasileira de comercialização de eletrodomésticos e eletroeletrônicos de luxo. Fundada em 1986, a empresa possui lojas nos principais estados brasileiros. A Empresa já patrocinou dois grandes clubes brasileiros. Em fevereiro de 2006 patrocionou o São Paulo Futebol Clube, estampando sua marca nas mangas da camisa, parceria essa que durou até inicio de 2009, quando passou a patrocinar a Sociedade Esportiva Palmeiras com sua marca também nas mangas da camisa.','A','FastShop', 1,'fastshop.jpg');
insert into loja (id, descricao, localizacao, nome, shopping_id, logo) values (20,'C&A é uma cadeia internacional de lojas de vestuário. No Brasil, é a maior rede de lojas de departamento do país. Foi fundada nos Países Baixos em 1841 pelos irmãos Clemens e August como uma empresa têxtil.','B','C&A', 1,'cea.jpg');
insert into loja (id, descricao, localizacao, nome, shopping_id, logo) values (30,'A Fast Shop é uma rede de lojas brasileira de comercialização de eletrodomésticos e eletroeletrônicos de luxo. Fundada em 1986, a empresa possui lojas nos principais estados brasileiros. A Empresa já patrocinou dois grandes clubes brasileiros. Em fevereiro de 2006 patrocionou o São Paulo Futebol Clube, estampando sua marca nas mangas da camisa, parceria essa que durou até inicio de 2009, quando passou a patrocinar a Sociedade Esportiva Palmeiras com sua marca também nas mangas da camisa.','D','World Tennis', 1,'wtennis.jpg');


insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (100, 10, 'LED LCD LV3500 42 polegadas Full HD LG', 'Principais Características: TV LED LCD 42. , Resolução Full HD. , Conversor digital integrado. , 3 entradas HDMI.', 'prod1.jpg', 1999.00, 25);
insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (101, 10, 'Notebook HP Pavilion DM13260BR / 3GB /500GB de HD', 'Está procurando o desempenho de um notebook, com a portabilidade de um netbook e o design que apenas o HP Pavilion dm1 pode oferecer? Deseja estar conectado onde quer que esteja?Deseja ter todos os recursos de computação sem abrir mão de nada por um preço acessível?Apresentamos o HP Pavilion dm1 Entertainment PC, um notebook totalmente novo projetado com tecnologias e materiais avançados que oferece tudo aquilo que você estava esperando de um notebook.O HP Pavilion dm1 é muito mais potente que os netbooks e oferece um design que proporciona mais mobilidade em relação à maioria dos notebooks. É uma classe totalmente nova de notebook compacto para estudantes e profissionais móveis que procuram um equilíbrio ideal de energia e produtividade com a tecnologia HP CoolSense, que permite a adaptação a todas as temperaturas.Imagens e sons realistas', 'prod2.jpg', 1077.58, 10);
insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (102, 10, 'Smartphone Samsung Omnia W Windows Phone 7.5', 'Principais Características: TV LED LCD 42. , Resolução Full HD. , Conversor digital integrado. , 3 entradas HDMI.', 'prod3.jpg', 1167.25, 25);
insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (103, 10, 'WX7 16.2MP Panorâmica 3D Cartão 8GB', 'Principais Características: TV LED LCD 42. , Resolução Full HD. , Conversor digital integrado. , 3 entradas HDMI.', 'prod4.jpg', 628.15, 16);
insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (104, 10, 'iPad 2 Branco com 64GB e Wi-Fi + 3G', 'Principais Características: TV LED LCD 42. , Resolução Full HD. , Conversor digital integrado. , 3 entradas HDMI.', 'prod5.jpg', 2335.80, 50);
insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (105, 10, 'XBOX 360 Slim 250GB + Sensor Preto Kinect', 'Principais Características: TV LED LCD 42. , Resolução Full HD. , Conversor digital integrado. , 3 entradas HDMI.', 'prod6.jpg', 1167.30, 30);
insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (106, 10, 'Roteador Wireless 150 MBPS Linksys', 'Principais Características: TV LED LCD 42. , Resolução Full HD. , Conversor digital integrado. , 3 entradas HDMI.', 'prod7.jpg', 144.42, 10);
insert into Produtos (id, loja_id, nome, descricao, imagem, precoVenda, quantidade) values (107, 10, 'Multifuncional Duplex, Imprime em CD e DVD Epson', 'Principais Características: TV LED LCD 42. , Resolução Full HD. , Conversor digital integrado. , 3 entradas HDMI.', 'prod8.jpg', 987.70, 18);

insert into usuarios (id, nome, senha) values (100,'victor@gmail.com','victor');
insert into usuarios (id, nome, senha) values (101,'renato@gmail.com','renato');
insert into usuarios (id, nome, senha) values (102,'leandro@gmail.com','leandro');


insert into Member (id, name, email, phone_number) values (0, 'John Smith', 'john.smith@mailinator.com', '2125551212') 